import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
import RegisterForm from '@/components/RegisterForm';
import LoginForm from '@/components/LoginForm';
import Vault from '@/components/Vault';

export interface VaultItem {
  website: string;
  username: string;
  password: string;
}

export default function Home() {
  const [step, setStep] = useState<'login' | 'register' | 'vault'>('vault');
  const [vault, setVault] = useState<VaultItem[]>([]);
  const [vaultKey, setVaultKey] = useState('');

  useEffect(() => {
    const vault = window.sessionStorage.getItem('vault');
    const vaultKey = window.sessionStorage.getItem('vaultKey');

    if (vault) {
      setVault(JSON.parse(vault));
    }

    if (vaultKey) {
      setVaultKey(vaultKey);
      setStep('vault');
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {step === 'register' && (
          <RegisterForm setStep={setStep} setVaultKey={setVaultKey} />
        )}
        {step === 'login' && <LoginForm />}
        {step === 'vault' && <Vault vault={vault} vaultKey={vaultKey} />}
      </main>
    </>
  );
}
